#!/usr/bin/env bash
#displays the time for 12 hours and 59 minutes:
#+display hours from 0 to 12
#+display minutes from 1 to 59
Hour=0
minute=0
while [ $Hour -le 12 ]
do
	while [ $minute -le 59 ]
	do
		echo "Hour: $Hour"
		echo $minute
		minute=$((minute+1))
		if [ $minute -eq 60 ]
			minute=0
		fi
		hour=$((hour+1))
	done
done	
