#!/usr/bin/env bash
#displays the content of the current directory
#+In a list format
#+Where only the part of the name after the first dash is displayed
for file in *
do
    #check if file is not hidden and contains a dash
    if [[ file != .*file == *-* ]]
    then
        #remove everything before and including the first dash
        file=file#*-
        echo file
    fi
done
